// Database Model Types (from Prisma schema)
// These types are generated by Prisma, but we provide them here for reference

export interface Customer {
  id: number
  companyId: string
  name: string | null
  address: string | null
  phone: string | null
  email: string | null
  active: boolean
  archived: boolean
  createdAt: Date | null
  updatedAt: Date | null
  lastSynced: Date
}

export interface Site {
  id: number
  companyId: string
  customerId: number
  name: string
  address: string | null
  active: boolean
  archived: boolean
  createdAt: Date | null
  updatedAt: Date | null
  lastSynced: Date
}

export interface Job {
  id: number
  companyId: string
  customerId: number | null
  siteId: number | null
  reference: string | null
  name: string | null
  description: string | null
  status: string | null
  jobType: string | null
  priority: string | null
  scheduledStart: Date | null
  scheduledEnd: Date | null
  completedAt: Date | null
  archived: boolean
  createdAt: Date | null
  updatedAt: Date | null
  lastSynced: Date
}

export interface Quote {
  id: number
  companyId: string
  customerId: number | null
  siteId: number | null
  reference: string | null
  name: string | null
  description: string | null
  status: string | null
  totalValue: string | null
  dateCreated: Date | null
  validUntil: Date | null
  convertedToJobId: number | null
  convertedAt: Date | null
  archived: boolean
  updatedAt: Date | null
  lastSynced: Date
}

export interface Employee {
  id: number
  companyId: string
  fullName: string
  email: string | null
  phone: string | null
  role: string | null
  active: boolean
  archived: boolean
  createdAt: Date | null
  updatedAt: Date | null
  lastSynced: Date
}

export interface Asset {
  id: number
  companyId: string
  siteId: number | null
  name: string
  type: string | null
  serialNumber: string | null
  manufacturer: string | null
  model: string | null
  active: boolean
  archived: boolean
  createdAt: Date | null
  updatedAt: Date | null
  lastSynced: Date
}

export interface Contractor {
  id: number
  companyId: string
  fullName: string | null
  companyName: string | null
  email: string | null
  phone: string | null
  active: boolean
  archived: boolean
  createdAt: Date | null
  updatedAt: Date | null
  lastSynced: Date
}

// ============================================
// SYNC OPTIONS
// ============================================

export interface SyncOptions {
  companyId: string
  syncType: "full" | "incremental" | "historical" // historical = includes archived
  entityTypes?: ("customers" | "sites" | "jobs" | "quotes" | "employees" | "assets" | "contractors")[]
  onProgress?: (message: string) => void
}

export interface SyncResult {
  entityType: string
  recordsFetched: number
  recordsCreated: number
  recordsUpdated: number
  recordsArchived: number
  durationMs: number
  status: "completed" | "failed"
  error?: string
}
